routes/web.php
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Auth::routes();


// Route::middleware('auth')->group(function(){
    Route::get('logout', 'Auth\LoginController@logout');
Route::get('/', 'HomeController@index')->name('home.index');

Route::prefix('self-enrol')->middleware('auth')->name('self-enrol.')->group(function () {
    Route::get('/', 'SelfEnrolController@index')->name('index');
    Route::post('enrol', 'SelfEnrolController@enrol')->name('enrol');
});
// Route::namespace('Admin')->middleware('auth')->group(function(){
//     Route::prefix('activity')->name('activity.')->group(function () {
//         Route::get('attendance/{id}/{section}', 'ActivityController@attendance')->name('attendance');
//         Route::get('attendance/{id?}/result-by-detail/{activityCalendarDetailId}', 'ActivityController@resultAttendanceByDetail')->name('result-attendance-by-detail');
//         Route::post('attendance/overridden/{activityCalendarDetailId}', 'ActivityController@overridenAttendance')->name('attendance-overridden');
//         Route::post('attendance/{id}/calendar', 'ActivityController@updateCalendar')->name('updatecalendar');
//         Route::post('attendance/{id}/export', 'ActivityController@exportResultAttendance')->name('attendance.export');        
//         Route::get('participant/{id}', 'ActivityController@participant')->name('participant');
//         Route::get('participant/potential-users/{id}', 'ActivityController@getPotentialUser')->name('get-potential-user');
//         Route::post('participant/enrol-users/{method?}', 'ActivityController@enrolUser')->name('enrol-user');
//         Route::post('participant/unenrol/{activityid}', 'ActivityController@unenrolUser')->name('unenrol-user');       
//         Route::get('statistic/{id}', 'ActivityController@statistic')->name('statistic');
//     });
// });
Route::namespace('Admin')->middleware('auth')->prefix('admin')->name('admin.')->group(function () {
    Route::prefix('machine')->name('machine.')->group(function () {
        Route::get('/', 'MachineController@index')->name('index');
        Route::get('index', 'MachineController@index')->name('index');
        Route::get('create', 'MachineController@create')->name('create');
        Route::post('store', 'MachineController@store')->name('store');
        Route::get('edit/{id}', 'MachineController@edit')->name('edit');
        Route::post('update', 'MachineController@update')->name('update');
        Route::get('update-identity-user/{id}', 'MachineController@showIdentityUser')->name('update-identity-user');
        Route::get('update-identity-user/{id}/get-potential-user', 'MachineController@getPotentialUser')->name('get-potential-user');
        Route::post('update-identity-user/{id}/store-identity-user', 'MachineController@storeIdentityUser')->name('store-identity-user');
        Route::post('delete-identity-user', 'MachineController@deleteIdentityUser')->name('delete-identity-user');
        Route::post('delete', 'MachineController@destroy')->name('delete');
    });

    Route::prefix('room')->name('room.')->group(function () {
        Route::get('/', 'RoomController@index')->name('index');
        Route::get('index', 'RoomController@index')->name('index');
        Route::get('create', 'RoomController@create')->name('create');
        Route::post('store', 'RoomController@store')->name('store');
        Route::get('edit/{id}', 'RoomController@edit')->name('edit');
        Route::get('assign-machine/{id}', 'RoomController@assignMachine')->name('assignmachine');
        Route::post('store-assign-machine', 'RoomController@storeAssignMachine')->name('storeassign');
        Route::post('update', 'RoomController@update')->name('update');
        Route::post('delete', 'RoomController@destroy')->name('delete');
    });
    
    Route::prefix('roomgroup')->name('roomgroup.')->group(function () {
        Route::get('create', 'RoomGroupController@create')->name('create');
        Route::post('store', 'RoomGroupController@store')->name('store');
        Route::get('edit/{id}', 'RoomGroupController@edit')->name('edit');
        Route::post('update', 'RoomGroupController@update')->name('update');
        Route::post('delete', 'RoomGroupController@destroy')->name('delete');
    });
    Route::prefix('holiday')->name('holiday.')->group(function () {
        Route::get('/', 'HolidayController@index')->name('index');
        Route::get('index', 'HolidayController@index')->name('index');
        Route::get('create', 'HolidayController@create')->name('create');
        Route::post('store', 'HolidayController@store')->name('store');
        Route::get('edit/{id}', 'HolidayController@edit')->name('edit');
        Route::post('update', 'HolidayController@update')->name('update');
        Route::post('delete', 'HolidayController@destroy')->name('delete');
    });


     Route::prefix('activitycategory')->name('activitycategory.')->group(function () {
        Route::get('create', 'ActivityCategoryController@create')->name('create');
        Route::post('store', 'ActivityCategoryController@store')->name('store');
        Route::get('edit/{id}', 'ActivityCategoryController@edit')->name('edit');
        Route::post('update', 'ActivityCategoryController@update')->name('update');
        Route::post('delete', 'ActivityCategoryController@destroy')->name('delete');
    });

    Route::prefix('activity')->name('activity.')->group(function () {
        Route::get('/', 'ActivityController@index')->name('index');
        Route::get('index', 'ActivityController@index')->name('index');
        Route::get('create', 'ActivityController@create')->name('create');
        Route::post('store', 'ActivityController@store')->name('store');
        Route::get('edit/{id}', 'ActivityController@edit')->name('edit');
        Route::post('update/{id}', 'ActivityController@update')->name('update');
        Route::get('subview-table-frequency/{frequency}/{shift?}', 'ActivityController@subViewTableFrequency')->name('subviewtablefrequency');
        Route::get('attendance/{id}/{section}', 'ActivityController@attendance')->name('attendance');
        Route::get('attendance/{id?}/result-by-detail/{activityCalendarDetailId}', 'ActivityController@resultAttendanceByDetail')->name('result-attendance-by-detail');
        Route::post('attendance/overridden/{activityCalendarDetailId}', 'ActivityController@overridenAttendance')->name('attendance-overridden');
        Route::post('attendance/{id}/calendar', 'ActivityController@updateCalendar')->name('updatecalendar');
        Route::post('attendance/{id}/export', 'ActivityController@exportResultAttendance')->name('attendance.export');        
        Route::get('participant/{id}', 'ActivityController@participant')->name('participant');
        Route::get('participant/potential-users/{id}', 'ActivityController@getPotentialUser')->name('get-potential-user');
        Route::post('participant/enrol-users/{method?}', 'ActivityController@enrolUser')->name('enrol-user');
        Route::post('participant/unenrol/{activityid}', 'ActivityController@unenrolUser')->name('unenrol-user');
       
        Route::get('statistic/{id}', 'ActivityController@statistic')->name('statistic');
        Route::post('delete', 'ActivityController@destroy')->name('delete');
    });
    Route::prefix('user')->name('user.')->group(function () {
        Route::get('/', 'UserController@index')->name('index');
        Route::get('index', 'UserController@index')->name('index');
        Route::get('create', 'UserController@create')->name('create');
        Route::post('store', 'UserController@store')->name('store');
        Route::get('edit/{id}', 'UserController@edit')->name('edit');
        Route::post('update', 'UserController@update')->name('update');
        Route::post('delete', 'UserController@destroy')->name('delete');
    });
    
    Route::prefix('cohort')->name('cohort.')->group(function () {
        Route::get('/', 'CohortController@index')->name('index');
        Route::get('index', 'CohortController@index')->name('index');
        Route::get('create', 'CohortController@create')->name('create');
        Route::post('store', 'CohortController@store')->name('store');
        Route::get('edit/{id}', 'CohortController@edit')->name('edit');
        Route::get('assign-user/{id}', 'CohortController@assignMachine')->name('assignuser');
        Route::post('store-assign-user', 'CohortController@storeAssignMachine')->name('storeassign');
        Route::post('update', 'CohortController@update')->name('update');
        Route::post('delete', 'CohortController@destroy')->name('delete');
    });

    Route::prefix('shift')->name('shift.')->group(function () {
        Route::get('/', 'ShiftController@index')->name('index');
        Route::get('index/{id?}', 'ShiftController@index')->name('index');
        Route::get('create', 'ShiftController@create')->name('create');
        Route::post('store', 'ShiftController@store')->name('store');
        Route::get('edit/{id}', 'ShiftController@edit')->name('edit');
        Route::post('update', 'ShiftController@update')->name('update');
        Route::post('delete', 'ShiftController@destroy')->name('delete');
    });

    Route::prefix('config')->name('config.')->group(function () {
        Route::get('/{section?}', 'ConfigController@index')->name('index');
        Route::post('update/{section?}', 'ConfigController@update')->name('update');

        Route::get('role/create', 'RoleController@create')->name('create-role');
        Route::post('role/store', 'RoleController@store')->name('store-role');
        Route::get('role/edit/{id}', 'RoleController@edit')->name('edit-role');
        Route::post('role/update/{id}', 'RoleController@update')->name('update-role');
        Route::post('role/delete', 'RoleController@destroy')->name('delete-role');

app/ActivityCategory.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class ActivityCategory extends Model
{
    protected $table = 'activity_categories';
    protected $fillable = [
        'activitycategorycode', 'name', 'note', 'depth', 'path', 'parent'
    ];

    public $timestamps = false;

    public function activities()
    {
        return $this->hasMany('App\Activity');
    }

    public static function loadParents($exceptCategoryId = -1){
        $activityCategories = self::select('id', 'name', 'depth', 'path')->orderBy('path', 'ASC')->get();
        $parents = [];
        if($exceptCategoryId != 0)
            $parents = $parents + ['0' => 'Hệ thống'];

        foreach($activityCategories as $category){
            if($category->id == $exceptCategoryId)
                continue;
            $nodes = explode('/', $category->path);
            unset($nodes[0]);
            $parents[$category->id] = '';
            foreach($nodes as $node){ 
                if($node == $exceptCategoryId){
                    unset($parents[$category->id]);
                    break;
                }
                if($node==$category->id)
                    $parents[$category->id] .= $category->name; 
                else{
                    $curCategory = $activityCategories->find($node);
                    $name = $curCategory ? $curCategory->name :'';
                    $parents[$category->id] .= $name .' / '; 
                }                
            }
        }
        return $parents;
    }
    
}

app/Http/Controllers/Admin/ActivityCategoryController.php
<?php

namespace App\Http\Controllers\Admin;

use App\ActivityCategory;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Input;
use Illuminate\Support\Facades\DB;
use Constraint;

class ActivityCategoryController extends \App\Http\Controllers\Controller
{
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        \CheckPermission::requireCapability('system:manage_system', \ContextSystem::instance());
        $currentCategoryId = Input::get('activitycategory', 0);        
        $parents = ActivityCategory::loadParents();

        return view('admin.activitycategory.create', compact('currentCategoryId', 'parents'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = $request->all();
        $msgErrors = [];
        if(ActivityCategory::where('activitycategorycode', $data['activitycategorycode'])->first()){
            $msgErrors['activitycategorycode']='Mã danh mục hoạt động đã tồn tại!';
        }
        if(!empty($msgErrors) > 0) return redirect()->back()->withInput()->withErrors($msgErrors);
        if($data['parent'] != 0)
            $activityCategoryParent = ActivityCategory::select('id', 'depth', 'path')->findOrFail($data['parent']);
        else{
            $activityCategoryParent = new \stdClass();
            $activityCategoryParent->path='';
            $activityCategoryParent->depth = 0;
        }
        
        $activityCategory = ActivityCategory::create($data); 
        $activityCategory->depth = $activityCategoryParent->depth + 1;
        $activityCategory->path = $activityCategoryParent->path . '/' . $activityCategory->id;
        $activityCategory->save();
        return redirect()->route('admin.activity.index', ['activitycategory'=> $activityCategory->id]);
    }
    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\ActivityCategory  $activitycategory
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        \CheckPermission::requireCapability('system:manage_system', \ContextSystem::instance());

        $activityCategory = ActivityCategory::findOrFail($id);
        $parents = ActivityCategory::loadParents($id);
        return view('admin.activitycategory.edit', compact('activityCategory', 'parents'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\ActivityCategory  $activitycategory
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request)
    {
        $data = $request->all();
        $activityCategory = ActivityCategory::findOrFail($data['id']);
        $msgErrors = [];
        if($activityCategory->activitycategorycode != $data['activitycategorycode']  && ActivityCategory::where('activitycategorycode', $data['activitycategorycode'])->first()){
            $msgErrors['activitycategorycode'] = 'Mã danh mục hoạt động đã tồn tại!';
        }
        
       if(!empty($msgErrors)) return redirect()->back()->withInput()->withErrors($msgErrors);
        if($activityCategory->parent != $data['parent']){
            if($data['parent'] != 0)
                $activityCategoryParent = ActivityCategory::select('id', 'depth', 'path')->findOrFail($data['parent']);
            else{
                $activityCategoryParent = new \stdClass();
                $activityCategoryParent->path='';
                $activityCategoryParent->depth = 0;
            }
        }else {
            unset($data['parent']);
        }
        $activityCategory->update($data);
        if(isset($activityCategoryParent)){
            //Tính sự thay đổi depth
            $newDepth = $activityCategoryParent->depth + 1;
            $subDepth = $newDepth - $activityCategory->depth;
            $oldPath = $activityCategory->path;
            $newPath = $activityCategoryParent->path . '/' . $activityCategory->id;
            //update this category
            $activityCategory->depth = $newDepth;
            $activityCategory->path = $newPath;
            $activityCategory->save();
            //update child nodes
            // $childAactivityCategories = ActivityCategory::where('path', 'like', $activityCategory->path . '%')->get();
            DB::table('activity_categories')->where('path', 'like',  "$oldPath/%")
                                        ->update(['depth' => DB::raw("depth + $subDepth"),
                                                    'path' => DB::raw("REPLACE(path, '$oldPath', '$newPath')")]);


        }
        return redirect()->route('admin.activity.index', ['activitycategory'=> $activityCategory->id]); 
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\ActivityCategory  $activitycategory
     * @return \Illuminate\Http\Response
     */
    public function destroy(ActivityCategory $activitycategory)
    {
        //
    }
}

resources/views/admin/activitycategory/create.blade.php
@extends('layouts.master')

@section('title', 'Thêm danh mục hoạt động')

@section ('content')


<div class="box box-info">
    <div class="box-header with-border">
        <h3 class="box-title">Thêm danh mục hoạt động</h3>
        <div class="box-tools pull-right">
            <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
            </button>
            <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
        </div>
    </div>
        <!-- /.box-header -->
    <div class="box-body">
        <form action="{{route('admin.activitycategory.store')}}" id="form-department" method="POST" class="form-horizontal" >
            @csrf
            <div class="form-group">
                <label class="control-label col-md-2">
                    Mục cha:
                </label>
                <div class="col-md-8">
                    <select name="parent" id="" class="form-control">
                    <?php
                        $currentCategory = old('parent') ? old('parent') : $currentCategoryId;
                    ?>
                        @foreach($parents as $key => $value)
                            <option {{$currentCategory == $key ? 'selected':''}} value="{{$key}}">{{$value}}</option>        
                        @endforeach
                    </select>
                </div>
            </div>
            <div class="form-group">
                <label class="control-label col-md-2">
                    Mã danh mục hoạt động:
                    <span class="require-field">(*)</span>
                </label>
                <div class="col-md-3">
                    <input type="text" name="activitycategorycode" value="{{old('activitycategorycode')}}" class="form-control">
                </div>
            </div>
            <div class="form-group">
                <label class="control-label col-md-2">
                    Tên danh mục hoạt động: 
                    <span class="require-field">(*)</span>
                </label>
                <div class="col-md-5">
                    <input type="text" name="name" class="form-control" value="{{old('name')}}">
                </div>
            </div>
            <div class="form-group">
                <label class="control-label col-md-2">
                    Ghi chú:
                </label>
                <div class="col-md-10">
                    <input type="text" name="note" value = "{{old('note')}}" class="form-control">
                </div>
            </div>

            <div class="form-group">
                <div class="col-sm-10 col-sm-offset-2">
                    <button type="submit" class="btn btn-primary">Lưu</button>
                </div>
            </div>
        </form>
    </div>
    <!-- box body -->
</div>
@stop

@section('scripts')

	<script type="text/javascript" src="{{ asset('js/jquery.validate.min.js') }}"></script>
	<script type="text/javascript" src="{{ asset('js/additional-methods.min.js') }}"></script>
    <script type="text/javascript" src="{{ asset('js/pages/activitycategory/create.js') }}"></script>
	<script type="text/javascript">
		$(function(){
			@if($errors->has('activitycategorycode'))
				$('form#form-department').validate().showErrors({
				 	"activitycategorycode": "{{$errors->first('activitycategorycode')}}"
				});
          	@endif
          
		});

	</script>
@stop

resources/views/admin/activitycategory/edit.blade.php
@extends('layouts.master')

@section('title', 'Sửa danh mục hoạt động')

@section ('content')


<div class="box box-info">
    <div class="box-header with-border">
        <h3 class="box-title">Sửa danh mục hoạt động</h3>
        <div class="box-tools pull-right">
            <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
            </button>
            <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
        </div>
    </div>
        <!-- /.box-header -->
    <div class="box-body">
        <form action="{{route('admin.activitycategory.update')}}" id="form-department" method="POST" class="form-horizontal" >
            @csrf
            <input type="hidden" name="id" value="{{$activityCategory->id}}">
            <div class="form-group">
                <label class="control-label col-md-2">
                    Mục cha:
                </label>
                <div class="col-md-8">
                    <select name="parent" id="" class="form-control">
                    <?php
                        $currentGroup = old('parent') ? old('parent') : $activityCategory->parent;
                    ?>
                        @foreach($parents as $key => $value)
                            <option {{$currentGroup == $key ? 'selected':''}} value="{{$key}}">{{$value}}</option>        
                        @endforeach
                    </select>
                </div>
            </div>
            <div class="form-group">
                <label class="control-label col-md-2">
                    Mã danh mục hoạt động:
                    <span class="require-field">(*)</span>
                </label>
                <div class="col-md-3">
                    <input type="text" name="activitycategorycode" value="{{old('activitycategorycode') ? old('activitycategorycode') : $activityCategory->activitycategorycode}}" class="form-control">
                </div>
            </div>
            <div class="form-group">
                <label class="control-label col-md-2">
                    Tên danh mục hoạt động: 
                    <span class="require-field">(*)</span>
                </label>
                <div class="col-md-5">
                    <input type="text" name="name" class="form-control" value="{{old('name') ? old('name') : $activityCategory->name}}">
                </div>
            </div>
            <div class="form-group">
                <label class="control-label col-md-2">
                    Ghi chú:
                </label>
                <div class="col-md-10">
                    <input type="text" name="note" value = "{{old('note') ? old('note') : $activityCategory->note}}" class="form-control">
                </div>
            </div>

            <div class="form-group">
                <div class="col-sm-10 col-sm-offset-2">
                    <button type="submit" class="btn btn-primary">Lưu</button>
                </div>
            </div>
        </form>
    </div>
    <!-- box body -->
</div>
@stop

@section('scripts')

	<script type="text/javascript" src="{{ asset('js/jquery.validate.min.js') }}"></script>
	<script type="text/javascript" src="{{ asset('js/additional-methods.min.js') }}"></script>
    <script type="text/javascript" src="{{ asset('js/pages/activitycategory/create.js') }}"></script>
	<script type="text/javascript">
		$(function(){
			@if($errors->has('activitycategorycode'))
				$('form#form-department').validate().showErrors({
				 	"activitycategorycode": "{{$errors->first('activitycategorycode')}}"
				});
          	@endif
          
		});

	</script>
@stop