routes/web.php
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Auth::routes();


// Route::middleware('auth')->group(function(){
    Route::get('logout', 'Auth\LoginController@logout');
Route::get('/', 'HomeController@index')->name('home.index');

Route::prefix('self-enrol')->middleware('auth')->name('self-enrol.')->group(function () {
    Route::get('/', 'SelfEnrolController@index')->name('index');
    Route::post('enrol', 'SelfEnrolController@enrol')->name('enrol');
});
// Route::namespace('Admin')->middleware('auth')->group(function(){
//     Route::prefix('activity')->name('activity.')->group(function () {
//         Route::get('attendance/{id}/{section}', 'ActivityController@attendance')->name('attendance');
//         Route::get('attendance/{id?}/result-by-detail/{activityCalendarDetailId}', 'ActivityController@resultAttendanceByDetail')->name('result-attendance-by-detail');
//         Route::post('attendance/overridden/{activityCalendarDetailId}', 'ActivityController@overridenAttendance')->name('attendance-overridden');
//         Route::post('attendance/{id}/calendar', 'ActivityController@updateCalendar')->name('updatecalendar');
//         Route::post('attendance/{id}/export', 'ActivityController@exportResultAttendance')->name('attendance.export');        
//         Route::get('participant/{id}', 'ActivityController@participant')->name('participant');
//         Route::get('participant/potential-users/{id}', 'ActivityController@getPotentialUser')->name('get-potential-user');
//         Route::post('participant/enrol-users/{method?}', 'ActivityController@enrolUser')->name('enrol-user');
//         Route::post('participant/unenrol/{activityid}', 'ActivityController@unenrolUser')->name('unenrol-user');       
//         Route::get('statistic/{id}', 'ActivityController@statistic')->name('statistic');
//     });
// });
Route::namespace('Admin')->middleware('auth')->prefix('admin')->name('admin.')->group(function () {
    Route::prefix('machine')->name('machine.')->group(function () {
        Route::get('/', 'MachineController@index')->name('index');
        Route::get('index', 'MachineController@index')->name('index');
        Route::get('create', 'MachineController@create')->name('create');
        Route::post('store', 'MachineController@store')->name('store');
        Route::get('edit/{id}', 'MachineController@edit')->name('edit');
        Route::post('update', 'MachineController@update')->name('update');
        Route::get('update-identity-user/{id}', 'MachineController@showIdentityUser')->name('update-identity-user');
        Route::get('update-identity-user/{id}/get-potential-user', 'MachineController@getPotentialUser')->name('get-potential-user');
        Route::post('update-identity-user/{id}/store-identity-user', 'MachineController@storeIdentityUser')->name('store-identity-user');
        Route::post('delete-identity-user', 'MachineController@deleteIdentityUser')->name('delete-identity-user');
        Route::post('delete', 'MachineController@destroy')->name('delete');
    });

    Route::prefix('room')->name('room.')->group(function () {
        Route::get('/', 'RoomController@index')->name('index');
        Route::get('index', 'RoomController@index')->name('index');
        Route::get('create', 'RoomController@create')->name('create');
        Route::post('store', 'RoomController@store')->name('store');
        Route::get('edit/{id}', 'RoomController@edit')->name('edit');
        Route::get('assign-machine/{id}', 'RoomController@assignMachine')->name('assignmachine');
        Route::post('store-assign-machine', 'RoomController@storeAssignMachine')->name('storeassign');
        Route::post('update', 'RoomController@update')->name('update');
        Route::post('delete', 'RoomController@destroy')->name('delete');
    });
    
    Route::prefix('roomgroup')->name('roomgroup.')->group(function () {
        Route::get('create', 'RoomGroupController@create')->name('create');
        Route::post('store', 'RoomGroupController@store')->name('store');
        Route::get('edit/{id}', 'RoomGroupController@edit')->name('edit');
        Route::post('update', 'RoomGroupController@update')->name('update');
        Route::post('delete', 'RoomGroupController@destroy')->name('delete');
    });
    Route::prefix('holiday')->name('holiday.')->group(function () {
        Route::get('/', 'HolidayController@index')->name('index');
        Route::get('index', 'HolidayController@index')->name('index');
        Route::get('create', 'HolidayController@create')->name('create');
        Route::post('store', 'HolidayController@store')->name('store');
        Route::get('edit/{id}', 'HolidayController@edit')->name('edit');
        Route::post('update', 'HolidayController@update')->name('update');
        Route::post('delete', 'HolidayController@destroy')->name('delete');
    });


     Route::prefix('activitycategory')->name('activitycategory.')->group(function () {
        Route::get('create', 'ActivityCategoryController@create')->name('create');
        Route::post('store', 'ActivityCategoryController@store')->name('store');
        Route::get('edit/{id}', 'ActivityCategoryController@edit')->name('edit');
        Route::post('update', 'ActivityCategoryController@update')->name('update');
        Route::post('delete', 'ActivityCategoryController@destroy')->name('delete');
    });

    Route::prefix('activity')->name('activity.')->group(function () {
        Route::get('/', 'ActivityController@index')->name('index');
        Route::get('index', 'ActivityController@index')->name('index');
        Route::get('create', 'ActivityController@create')->name('create');
        Route::post('store', 'ActivityController@store')->name('store');
        Route::get('edit/{id}', 'ActivityController@edit')->name('edit');
        Route::post('update/{id}', 'ActivityController@update')->name('update');
        Route::get('subview-table-frequency/{frequency}/{shift?}', 'ActivityController@subViewTableFrequency')->name('subviewtablefrequency');
        Route::get('attendance/{id}/{section}', 'ActivityController@attendance')->name('attendance');
        Route::get('attendance/{id?}/result-by-detail/{activityCalendarDetailId}', 'ActivityController@resultAttendanceByDetail')->name('result-attendance-by-detail');
        Route::post('attendance/overridden/{activityCalendarDetailId}', 'ActivityController@overridenAttendance')->name('attendance-overridden');
        Route::post('attendance/{id}/calendar', 'ActivityController@updateCalendar')->name('updatecalendar');
        Route::post('attendance/{id}/export', 'ActivityController@exportResultAttendance')->name('attendance.export');        
        Route::get('participant/{id}', 'ActivityController@participant')->name('participant');
        Route::get('participant/potential-users/{id}', 'ActivityController@getPotentialUser')->name('get-potential-user');
        Route::post('participant/enrol-users/{method?}', 'ActivityController@enrolUser')->name('enrol-user');
        Route::post('participant/unenrol/{activityid}', 'ActivityController@unenrolUser')->name('unenrol-user');
       
        Route::get('statistic/{id}', 'ActivityController@statistic')->name('statistic');
        Route::post('delete', 'ActivityController@destroy')->name('delete');
    });
    Route::prefix('user')->name('user.')->group(function () {
        Route::get('/', 'UserController@index')->name('index');
        Route::get('index', 'UserController@index')->name('index');
        Route::get('create', 'UserController@create')->name('create');
        Route::post('store', 'UserController@store')->name('store');
        Route::get('edit/{id}', 'UserController@edit')->name('edit');
        Route::post('update', 'UserController@update')->name('update');
        Route::post('delete', 'UserController@destroy')->name('delete');
    });
    
    Route::prefix('cohort')->name('cohort.')->group(function () {
        Route::get('/', 'CohortController@index')->name('index');
        Route::get('index', 'CohortController@index')->name('index');
        Route::get('create', 'CohortController@create')->name('create');
        Route::post('store', 'CohortController@store')->name('store');
        Route::get('edit/{id}', 'CohortController@edit')->name('edit');
        Route::get('assign-user/{id}', 'CohortController@assignMachine')->name('assignuser');
        Route::post('store-assign-user', 'CohortController@storeAssignMachine')->name('storeassign');
        Route::post('update', 'CohortController@update')->name('update');
        Route::post('delete', 'CohortController@destroy')->name('delete');
    });

    Route::prefix('shift')->name('shift.')->group(function () {
        Route::get('/', 'ShiftController@index')->name('index');
        Route::get('index/{id?}', 'ShiftController@index')->name('index');
        Route::get('create', 'ShiftController@create')->name('create');
        Route::post('store', 'ShiftController@store')->name('store');
        Route::get('edit/{id}', 'ShiftController@edit')->name('edit');
        Route::post('update', 'ShiftController@update')->name('update');
        Route::post('delete', 'ShiftController@destroy')->name('delete');
    });

    Route::prefix('config')->name('config.')->group(function () {
        Route::get('/{section?}', 'ConfigController@index')->name('index');
        Route::post('update/{section?}', 'ConfigController@update')->name('update');

        Route::get('role/create', 'RoleController@create')->name('create-role');
        Route::post('role/store', 'RoleController@store')->name('store-role');
        Route::get('role/edit/{id}', 'RoleController@edit')->name('edit-role');
        Route::post('role/update/{id}', 'RoleController@update')->name('update-role');
        Route::post('role/delete', 'RoleController@destroy')->name('delete-role');

app/Holiday.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Holiday extends Model
{
    public $table = 'holidays';
    
    protected $fillable = [
        'fullname', 'shortname', 'startdate', 'dayeveryyear', 'montheveryyear' ,'enddate', 'type', 'note'
    ];

    public $timestamps = false;
    
    public function activityCalendarDetails()
    {
        return $this->hasMany('App\ActivityCalendarDetail');
    }   
}

app/Http/Controllers/Admin/HolidayController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Holiday;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Input;
use App\Common\Constraint;
use App\Common\UtilityFunction;
class HolidayController extends \App\Http\Controllers\Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        \CheckPermission::requireCapability('system:manage_system', \ContextSystem::instance());
        $holidays = Holiday::paginate(Constraint::ITEMS_PER_PAGE); 
        $holidays->withPath(route('admin.holiday.index'));
        return view('admin.holiday.index', compact('holidays', 'keyword', 'status'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        \CheckPermission::requireCapability('system:manage_system', \ContextSystem::instance());
     
        return view('admin.holiday.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = $request->all();
        $msgErrors = [];
        if(Holiday::where('shortname', $data['shortname'])->first()){
            $msgErrors['shortname']='Tên viết tắt này đã tồn tại!';
        }

        //xét âm lịch
        // if($data['type'] == Constraint::HOLIDAY_TYPE_LUNAR){
        //     $msgErrors['startdate']='Ngày âm này không tồn tại!';
        //     $msgErrors['enddate']='Ngày âm này không tồn tại!';
        // }

        
        if($data['type'] == Constraint::HOLIDAY_TYPE_SOLAR){
            $dateEveryyear = explode('/', $data['startdate']);
            $dayEveryyear = $dateEveryyear[0];
            $monthEveryyear = $dateEveryyear[1];
            $data['startdate'] = null;
            //Xét không có ngày 29/02
            if($dayEveryyear >= 29 and $monthEveryyear == 2 )
                $msgErrors['startdate']='Ngày 29/02 không được phép!';
            $data['montheveryyear']=$monthEveryyear;
            $data['dayeveryyear'] = $dayEveryyear;
        }
        if(!empty($msgErrors) > 0) return redirect()->back()->withInput()->withErrors($msgErrors);

        if($data['type'] == Constraint::HOLIDAY_TYPE_SOLAR){
            $data['startdate'] = UtilityFunction::convertDateToInt($data['startdate'].'/2019');
            $data['enddate'] = UtilityFunction::convertDateToInt($data['enddate'].'/2019');
        }else if($data['type'] == Constraint::HOLIDAY_TYPE_SPECIFIC_DAY){
            $data['startdate'] = UtilityFunction::convertDateToInt($data['startdate']);
            $data['enddate'] = UtilityFunction::convertDateToInt($data['enddate']);
        }
        
        $dep = Holiday::create($data); 
        return redirect()->route('admin.holiday.index');

    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Holiday  $holiday
     * @return \Illuminate\Http\Response
     */
    public function show(Holiday $holiday)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Holiday  $holiday
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        \CheckPermission::requireCapability('system:manage_system', \ContextSystem::instance());

        $holiday = Holiday::findOrFail($id);
        return view('admin.holiday.edit', compact('holiday'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Holiday  $holiday
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request)
    {
        $data = $request->all();
        $holiday = Holiday::findOrFail($data['id']);
        $msgErrors = [];
        if($holiday->shortname != $data['shortname']  && Holiday::where('shortname', $data['shortname'])->first()){
            $msgErrors['shortname'] = 'Tên viết tắt này đã tồn tại!';
        }
         //xét âm lịch
        // if($data['type'] == Constraint::HOLIDAY_TYPE_LUNAR){
        //     $msgErrors['startdate']='Ngày âm này không tồn tại!';
        //     $msgErrors['enddate']='Ngày âm này không tồn tại!';
        // }
        if($data['type'] == Constraint::HOLIDAY_TYPE_SOLAR){
            $dateEveryyear = explode('/', $data['startdate']);
            $dayEveryyear = $dateEveryyear[0];
            $monthEveryyear = $dateEveryyear[1];
            $data['startdate'] = null;
            //Xét không có ngày 29/02
            if($dayEveryyear >= 29 and $monthEveryyear == 2 )
                $msgErrors['startdate']='Ngày 29/02 không được phép!';
            $data['montheveryyear']=$monthEveryyear;
            $data['dayeveryyear'] = $dayEveryyear;
        }

        if(!empty($msgErrors) > 0) return redirect()->back()->withInput()->withErrors($msgErrors);
        
        if($data['type'] == Constraint::HOLIDAY_TYPE_SOLAR){
            $data['startdate'] = UtilityFunction::convertDateToInt($data['startdate'].'/2019');
            $data['enddate'] = UtilityFunction::convertDateToInt($data['enddate'].'/2019');
        }else if($data['type'] == Constraint::HOLIDAY_TYPE_SPECIFIC_DAY){
            $data['startdate'] = UtilityFunction::convertDateToInt($data['startdate']);
            $data['enddate'] = UtilityFunction::convertDateToInt($data['enddate']);
        }
        
        $holiday->update($data);
        return redirect()->route('admin.holiday.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Holiday  $holiday
     * @return \Illuminate\Http\Response
     */
    public function destroy(Holiday $holiday)
    {
        //
    }
}

resources/views/admin/holiday/create.blade.php
@extends('layouts.master')

@section('title', 'Thêm ngày lễ')

@section ('content')


<div class="box box-info">
    <div class="box-header with-border">
        <h3 class="box-title">Thêm ngày lễ</h3>
        <div class="box-tools pull-right">
            <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
            </button>
            <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
        </div>
    </div>
        <!-- /.box-header -->
    <div class="box-body">
        <form action="{{route('admin.holiday.store')}}" id="form-department" method="POST" class="form-horizontal" >
            @csrf
            <div class="form-group">
                <label class="control-label col-md-2">
                    Tên đầy đủ:
                    <span class="require-field">(*)</span>
                </label>
                <div class="col-md-3">
                    <input type="text" name="fullname" value="{{old('fullname')}}" class="form-control">
                </div>
            </div>
            <div class="form-group">
                <label class="control-label col-md-2">
                    Tên viết tắt:
                    <span class="require-field">(*)</span>
                </label>
                <div class="col-md-2">
                    <input type="text" name="shortname" value="{{old('shortname')}}" class="form-control">
                </div>
            </div>
            <div class="form-group">
                <label class="control-label col-md-2">
                    Loại: 
                </label>
                <div class="col-md-3">
                    <select class="form-control" name="type" id="type-holiday">
                        <option {{old('type')==Constraint::HOLIDAY_TYPE_SPECIFIC_DAY ? 'selected':''}} value="{{Constraint::HOLIDAY_TYPE_SPECIFIC_DAY}}">Ngày cụ thể</option>
                        <option {{old('type')==Constraint::HOLIDAY_TYPE_SOLAR ? 'selected':''}} value="{{Constraint::HOLIDAY_TYPE_SOLAR}}">Dương lịch hằng năm</option>
                        <!-- <option {{old('type')==Constraint::HOLIDAY_TYPE_LUNAR ? 'selected':''}} value="{{Constraint::HOLIDAY_TYPE_LUNAR}}">Âm lịch hàng năm</option> -->
                    </select>
                </div>
            </div>
            <div class="input-daterange">
                <div class="form-group">
                    <label class="control-label col-md-2">
                        Ngày bắt đầu:
                        <span class="require-field">(*)</span>
                    </label>
                    <div class="col-md-3">
                        <div class="input-group date">
                            <div class="input-group-addon">
                                <i class="fa fa-calendar"></i>
                            </div>
                            <input type="text" name="startdate" class="form-control pull-right" id="startdate" value="{{old('startdate')}}">
                        </div>
                    </div>
                </div>
                
                <div class="form-group" id="div-enddate">
                    <label class="control-label col-md-2">
                        Ngày kết thúc:
                        <span class="require-field">(*)</span>
                    </label>
                    <div class="col-md-3">
                        <div class="input-group date">
                            <div class="input-group-addon">
                                <i class="fa fa-calendar"></i>
                            </div>
                            <input type="text" name="enddate" class="form-control pull-right" id="enddate" value="{{old('enddate')}}">
                        </div>
                    </div>
                </div>
            </div>
           
            <div class="form-group">
                <label class="control-label col-md-2">
                    Ghi chú:
                </label>
                <div class="col-md-10">
                    <input type="text" name="note" value = "{{old('note')}}" class="form-control">
                </div>
            </div>

            <div class="form-group">
                <div class="col-sm-10 col-sm-offset-2">
                    <button type="submit" class="btn btn-primary">Lưu</button>
                </div>
            </div>
        </form>
    </div>
    <!-- box body -->
</div>
@stop

@section('styles')
    <link rel="stylesheet" href="{{ asset('css/bootstrap-datepicker3.min.css') }}">
    <!-- <link rel="stylesheet" href="{{ asset('css/daterangepicker.css') }}"> -->
    <link rel="stylesheet" href="{{ asset('css/bootstrap-timepicker.min.css') }}">

@stop

@section('scripts')
    <script type="text/javascript" src="{{ asset('js/bootstrap-datepicker.min.js') }}"></script>
    <script type="text/javascript" src="{{ asset('js/bootstrap-datepicker.vi.js') }}"></script>
    <script type="text/javascript" src="{{ asset('js/bootstrap-timepicker.min.js') }}"></script>
    
	<script type="text/javascript" src="{{ asset('js/jquery.validate.min.js') }}"></script>
	<script type="text/javascript" src="{{ asset('js/additional-methods.min.js') }}"></script>
    <script type="text/javascript" src="{{ asset('js/pages/holiday/create.js') }}"></script>
	<script type="text/javascript">
		$(function(){
			@if($errors->has('shortname'))
				$('form#form-department').validate().showErrors({
				 	"shortname": "{{$errors->first('shortname')}}"
                });
                
              @endif
              @if($errors->has('start'))
				$('form#form-department').validate().showErrors({
				 	"start": "{{$errors->first('start')}}"
                });
                
              @endif
              @if($errors->has('enddate'))
				$('form#form-department').validate().showErrors({
				 	"enddate": "{{$errors->first('enddate')}}"
                });
                
              @endif
              
            @if(!$errors->any())
                $('#startdate').datepicker('setDate', new Date());
            @endif
          
		});

	</script>
@stop

resources/views/admin/holiday/edit.blade.php
@extends('layouts.master')

@section('title', 'Sửa ngày lễ')

@section ('content')


<div class="box box-info">
    <div class="box-header with-border">
        <h3 class="box-title">Sửa ngày lễ</h3>
        <div class="box-tools pull-right">
            <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
            </button>
            <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
        </div>
    </div>
        <!-- /.box-header -->
    <div class="box-body">
        <form action="{{route('admin.holiday.update')}}" id="form-department" method="POST" class="form-horizontal" >
            @csrf
            <input type="hidden" name="id" value="{{$holiday->id}}">
            <div class="form-group">
                <label class="control-label col-md-2">
                    Tên đầy đủ:
                    <span class="require-field">(*)</span>
                </label>
                <div class="col-md-3">
                    <input type="text" name="fullname" value="{{$errors->any() ? old('fullname') : $holiday->fullname}}" class="form-control">
                </div>
            </div>
            <div class="form-group">
                <label class="control-label col-md-2">
                    Tên viết tắt:
                    <span class="require-field">(*)</span>
                </label>
                <div class="col-md-2">
                    <input type="text" name="shortname" value="{{$errors->any() ? old('shortname') : $holiday->shortname}}" class="form-control">
                </div>
            </div>
            <div class="form-group">
                <label class="control-label col-md-2">
                    Loại: 
                </label>
                <div class="col-md-3">
                    <select class="form-control" name="type" id="type-holiday">
                        <?php $type = $errors->any() ? old('type') : $holiday->type; ?>
                        <option {{$type==Constraint::HOLIDAY_TYPE_SPECIFIC_DAY ? 'selected':''}} value="{{Constraint::HOLIDAY_TYPE_SPECIFIC_DAY}}">Ngày cụ thể</option>
                        <option {{$type==Constraint::HOLIDAY_TYPE_SOLAR ? 'selected':''}} value="{{Constraint::HOLIDAY_TYPE_SOLAR}}">Dương lịch hằng năm</option>
                        <!-- <option {{$type==Constraint::HOLIDAY_TYPE_LUNAR ? 'selected':''}} value="{{Constraint::HOLIDAY_TYPE_LUNAR}}">Âm lịch hàng năm</option> -->
                    </select>
                </div>
            </div>
            <?php
                $fullDate = $type==Constraint::HOLIDAY_TYPE_SPECIFIC_DAY;
                $startDate = $fullDate ? date('d/m/Y', $holiday->startdate) : $holiday->dayeveryyear.'/'.$holiday->montheveryyear;
            ?>
            <div class="input-daterange">
                <div class="form-group">
                    <label class="control-label col-md-2">
                        Ngày bắt đầu:
                        <span class="require-field">(*)</span>
                    </label>
                    <div class="col-md-3">
                        <div class="input-group date">
                            <div class="input-group-addon">
                                <i class="fa fa-calendar"></i>
                            </div>
                            <input type="text" name="startdate" class="form-control pull-right" id="startdate" value="{{$errors->any() ? old('startdate') : $startDate}}">
                        </div>
                    </div>
                </div>
                
                <div class="form-group" id="div-enddate">
                    <label class="control-label col-md-2">
                        Ngày kết thúc:
                        <span class="require-field">(*)</span>
                    </label>
                    <div class="col-md-3">
                        <div class="input-group date">
                            <div class="input-group-addon">
                                <i class="fa fa-calendar"></i>
                            </div>
                            <input type="text" name="enddate" class="form-control pull-right" id="enddate" value="{{$errors->any() ? old('enddate') : date('d/m/Y', $holiday->enddate)}}">
                        </div>
                    </div>
                </div>
            </div>
           
            <div class="form-group">
                <label class="control-label col-md-2">
                    Ghi chú:
                </label>
                <div class="col-md-10">
                    <input type="text" name="note" value = "{{$errors->any() ? old('note') : $holiday->note}}" class="form-control">
                </div>
            </div>

            <div class="form-group">
                <div class="col-sm-10 col-sm-offset-2">
                    <button type="submit" class="btn btn-primary">Lưu</button>
                </div>
            </div>
        </form>
    </div>
    <!-- box body -->
</div>
@stop

@section('styles')
    <link rel="stylesheet" href="{{ asset('css/bootstrap-datepicker3.min.css') }}">
    <!-- <link rel="stylesheet" href="{{ asset('css/daterangepicker.css') }}"> -->
    <link rel="stylesheet" href="{{ asset('css/bootstrap-timepicker.min.css') }}">

@stop

@section('scripts')
    <script type="text/javascript" src="{{ asset('js/bootstrap-datepicker.min.js') }}"></script>
    <script type="text/javascript" src="{{ asset('js/bootstrap-datepicker.vi.js') }}"></script>
    <script type="text/javascript" src="{{ asset('js/bootstrap-timepicker.min.js') }}"></script>
    
	<script type="text/javascript" src="{{ asset('js/jquery.validate.min.js') }}"></script>
	<script type="text/javascript" src="{{ asset('js/additional-methods.min.js') }}"></script>
    <script type="text/javascript" src="{{ asset('js/pages/holiday/create.js') }}"></script>
	<script type="text/javascript">
		$(function(){
			@if($errors->has('shortname'))
				$('form#form-department').validate().showErrors({
				 	"shortname": "{{$errors->first('shortname')}}"
                });
                
              @endif
              @if($errors->has('start'))
				$('form#form-department').validate().showErrors({
				 	"start": "{{$errors->first('start')}}"
                });
                
              @endif
              @if($errors->has('enddate'))
				$('form#form-department').validate().showErrors({
				 	"enddate": "{{$errors->first('enddate')}}"
                });
                
              @endif
              
            @if(!$errors->any())
                // $('#startdate').datepicker('setDate', new Date());
            @endif
          
		});

	</script>
@stop