routes/web.php
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Auth::routes();


// Route::middleware('auth')->group(function(){
    Route::get('logout', 'Auth\LoginController@logout');
Route::get('/', 'HomeController@index')->name('home.index');

Route::prefix('self-enrol')->middleware('auth')->name('self-enrol.')->group(function () {
    Route::get('/', 'SelfEnrolController@index')->name('index');
    Route::post('enrol', 'SelfEnrolController@enrol')->name('enrol');
});
// Route::namespace('Admin')->middleware('auth')->group(function(){
//     Route::prefix('activity')->name('activity.')->group(function () {
//         Route::get('attendance/{id}/{section}', 'ActivityController@attendance')->name('attendance');
//         Route::get('attendance/{id?}/result-by-detail/{activityCalendarDetailId}', 'ActivityController@resultAttendanceByDetail')->name('result-attendance-by-detail');
//         Route::post('attendance/overridden/{activityCalendarDetailId}', 'ActivityController@overridenAttendance')->name('attendance-overridden');
//         Route::post('attendance/{id}/calendar', 'ActivityController@updateCalendar')->name('updatecalendar');
//         Route::post('attendance/{id}/export', 'ActivityController@exportResultAttendance')->name('attendance.export');        
//         Route::get('participant/{id}', 'ActivityController@participant')->name('participant');
//         Route::get('participant/potential-users/{id}', 'ActivityController@getPotentialUser')->name('get-potential-user');
//         Route::post('participant/enrol-users/{method?}', 'ActivityController@enrolUser')->name('enrol-user');
//         Route::post('participant/unenrol/{activityid}', 'ActivityController@unenrolUser')->name('unenrol-user');       
//         Route::get('statistic/{id}', 'ActivityController@statistic')->name('statistic');
//     });
// });
Route::namespace('Admin')->middleware('auth')->prefix('admin')->name('admin.')->group(function () {
    Route::prefix('machine')->name('machine.')->group(function () {
        Route::get('/', 'MachineController@index')->name('index');
        Route::get('index', 'MachineController@index')->name('index');
        Route::get('create', 'MachineController@create')->name('create');
        Route::post('store', 'MachineController@store')->name('store');
        Route::get('edit/{id}', 'MachineController@edit')->name('edit');
        Route::post('update', 'MachineController@update')->name('update');
        Route::get('update-identity-user/{id}', 'MachineController@showIdentityUser')->name('update-identity-user');
        Route::get('update-identity-user/{id}/get-potential-user', 'MachineController@getPotentialUser')->name('get-potential-user');
        Route::post('update-identity-user/{id}/store-identity-user', 'MachineController@storeIdentityUser')->name('store-identity-user');
        Route::post('delete-identity-user', 'MachineController@deleteIdentityUser')->name('delete-identity-user');
        Route::post('delete', 'MachineController@destroy')->name('delete');
    });

    Route::prefix('room')->name('room.')->group(function () {
        Route::get('/', 'RoomController@index')->name('index');
        Route::get('index', 'RoomController@index')->name('index');
        Route::get('create', 'RoomController@create')->name('create');
        Route::post('store', 'RoomController@store')->name('store');
        Route::get('edit/{id}', 'RoomController@edit')->name('edit');
        Route::get('assign-machine/{id}', 'RoomController@assignMachine')->name('assignmachine');
        Route::post('store-assign-machine', 'RoomController@storeAssignMachine')->name('storeassign');
        Route::post('update', 'RoomController@update')->name('update');
        Route::post('delete', 'RoomController@destroy')->name('delete');
    });
    
    Route::prefix('roomgroup')->name('roomgroup.')->group(function () {
        Route::get('create', 'RoomGroupController@create')->name('create');
        Route::post('store', 'RoomGroupController@store')->name('store');
        Route::get('edit/{id}', 'RoomGroupController@edit')->name('edit');
        Route::post('update', 'RoomGroupController@update')->name('update');
        Route::post('delete', 'RoomGroupController@destroy')->name('delete');
    });
    Route::prefix('holiday')->name('holiday.')->group(function () {
        Route::get('/', 'HolidayController@index')->name('index');
        Route::get('index', 'HolidayController@index')->name('index');
        Route::get('create', 'HolidayController@create')->name('create');
        Route::post('store', 'HolidayController@store')->name('store');
        Route::get('edit/{id}', 'HolidayController@edit')->name('edit');
        Route::post('update', 'HolidayController@update')->name('update');
        Route::post('delete', 'HolidayController@destroy')->name('delete');
    });


     Route::prefix('activitycategory')->name('activitycategory.')->group(function () {
        Route::get('create', 'ActivityCategoryController@create')->name('create');
        Route::post('store', 'ActivityCategoryController@store')->name('store');
        Route::get('edit/{id}', 'ActivityCategoryController@edit')->name('edit');
        Route::post('update', 'ActivityCategoryController@update')->name('update');
        Route::post('delete', 'ActivityCategoryController@destroy')->name('delete');
    });

    Route::prefix('activity')->name('activity.')->group(function () {
        Route::get('/', 'ActivityController@index')->name('index');
        Route::get('index', 'ActivityController@index')->name('index');
        Route::get('create', 'ActivityController@create')->name('create');
        Route::post('store', 'ActivityController@store')->name('store');
        Route::get('edit/{id}', 'ActivityController@edit')->name('edit');
        Route::post('update/{id}', 'ActivityController@update')->name('update');
        Route::get('subview-table-frequency/{frequency}/{shift?}', 'ActivityController@subViewTableFrequency')->name('subviewtablefrequency');
        Route::get('attendance/{id}/{section}', 'ActivityController@attendance')->name('attendance');
        Route::get('attendance/{id?}/result-by-detail/{activityCalendarDetailId}', 'ActivityController@resultAttendanceByDetail')->name('result-attendance-by-detail');
        Route::post('attendance/overridden/{activityCalendarDetailId}', 'ActivityController@overridenAttendance')->name('attendance-overridden');
        Route::post('attendance/{id}/calendar', 'ActivityController@updateCalendar')->name('updatecalendar');
        Route::post('attendance/{id}/export', 'ActivityController@exportResultAttendance')->name('attendance.export');        
        Route::get('participant/{id}', 'ActivityController@participant')->name('participant');
        Route::get('participant/potential-users/{id}', 'ActivityController@getPotentialUser')->name('get-potential-user');
        Route::post('participant/enrol-users/{method?}', 'ActivityController@enrolUser')->name('enrol-user');
        Route::post('participant/unenrol/{activityid}', 'ActivityController@unenrolUser')->name('unenrol-user');
       
        Route::get('statistic/{id}', 'ActivityController@statistic')->name('statistic');
        Route::post('delete', 'ActivityController@destroy')->name('delete');
    });
    Route::prefix('user')->name('user.')->group(function () {
        Route::get('/', 'UserController@index')->name('index');
        Route::get('index', 'UserController@index')->name('index');
        Route::get('create', 'UserController@create')->name('create');
        Route::post('store', 'UserController@store')->name('store');
        Route::get('edit/{id}', 'UserController@edit')->name('edit');
        Route::post('update', 'UserController@update')->name('update');
        Route::post('delete', 'UserController@destroy')->name('delete');
    });
    
    Route::prefix('cohort')->name('cohort.')->group(function () {
        Route::get('/', 'CohortController@index')->name('index');
        Route::get('index', 'CohortController@index')->name('index');
        Route::get('create', 'CohortController@create')->name('create');
        Route::post('store', 'CohortController@store')->name('store');
        Route::get('edit/{id}', 'CohortController@edit')->name('edit');
        Route::get('assign-user/{id}', 'CohortController@assignMachine')->name('assignuser');
        Route::post('store-assign-user', 'CohortController@storeAssignMachine')->name('storeassign');
        Route::post('update', 'CohortController@update')->name('update');
        Route::post('delete', 'CohortController@destroy')->name('delete');
    });

    Route::prefix('shift')->name('shift.')->group(function () {
        Route::get('/', 'ShiftController@index')->name('index');
        Route::get('index/{id?}', 'ShiftController@index')->name('index');
        Route::get('create', 'ShiftController@create')->name('create');
        Route::post('store', 'ShiftController@store')->name('store');
        Route::get('edit/{id}', 'ShiftController@edit')->name('edit');
        Route::post('update', 'ShiftController@update')->name('update');
        Route::post('delete', 'ShiftController@destroy')->name('delete');
    });

    Route::prefix('config')->name('config.')->group(function () {
        Route::get('/{section?}', 'ConfigController@index')->name('index');
        Route::post('update/{section?}', 'ConfigController@update')->name('update');

        Route::get('role/create', 'RoleController@create')->name('create-role');
        Route::post('role/store', 'RoleController@store')->name('store-role');
        Route::get('role/edit/{id}', 'RoleController@edit')->name('edit-role');

app/Room.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Room extends Model
{
    protected $table = 'rooms';
    protected $fillable = [
        'roomcode', 'name', 'note', 'roomgroupid', 'status'
    ];

    public $timestamps = false;

    public function roomGroup()
    {
        return $this->belongsTo('App\RoomGroup','roomgroupid');
    }
  
    public function machines()
    {
        return $this->hasMany('App\RoomMachine');
    }
  
    public function acvtivityCalendars()
    {
        return $this->hasMany('App\ActivityCalendar');
    }
    
    public function acvtivityCalendarDetails()
    {
        return $this->hasMany('App\ActivityCalendarDetail');
    }
}

resources/views/admin/room/assignmachine.blade.php
@extends('layouts.master')

@section('title', 'Gán máy điểm danh')

@section ('content')

@if(empty($potentialMachines))

<div class="alert alert-warning">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
    <strong>Chú ý!</strong> Chưa có máy điểm danh nên không gán được
</div>

@else
    @if(session()->has('messageAssignMachine'))
        <div class="alert alert-success">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <strong>Thông báo!</strong> {{session()->get('messageAssignMachine')}}
        </div>

    @endif
<div class="box box-info">
    <div class="box-header with-border">
        <h3 class="box-title">Gán máy điểm danh cho {{$room->name}} ({{$room->roomcode}})</h3>
        <div class="box-tools pull-right">
            <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
            </button>
            <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
        </div>
    </div>
        <!-- /.box-header -->
    <div class="box-body">
        <div class="col-sm-12 col-md-12">
            <form id="form1" action="{{route('admin.room.storeassign')}}" method="post">
                @csrf
                <input type="hidden" name="id" value="{{$room->id}}">
                <div class="box-header">
                    <button class="btn btn-sm btn-flat btn-primary pull-right" type="submit">Lưu</button>
                </div>
                <div class="clearfix"></div>
                <div class="row">
                    <div class="col-sm-12 form-group col-md-offset-1 col-md-4">
                    <label for="" class="control-label text-center">Các máy đang sử dụng</label>
                        <select class="form-control" id="selUseMachines" name="usemachines[]" size="10" multiple>
                        @foreach($usedOwnRoomMachines as $machine)    
                        <option value="{{$machine->id}}">
                            {{$machine->machinecode}} {{!$machine->status ? '(Không hoạt động)':''}}
                        </option>
                        @endforeach     
                        </select>
                    </div>
                    <div class="col-sm-12 col-md-2">
                        <br><br><br>    
                        <button id="btnLeft" type="button" class="btn-success btn btn-flat col-md-12">
                            <i class="fa fa-angle-double-left"></i> 
                        </button>
                        &nbsp;&nbsp;
                        <button id="btnRight" type="button" class="btn btn-danger btn-flat col-md-12">
                            <i class="fa fa-angle-double-right"></i> 
                        </button>
                    </div>
                    <div class="col-sm-12 col-md-4 form-group">
                        <label for="" class="control-label text-center">Các máy tiềm năng</label>
                        <select id="selPotentialMachines" class="form-control" size="10" multiple>
                            @foreach($potentialMachines as $machine)    
                            <option value="{{$machine->id}}">
                                {{$machine->machinecode}} {{ !$machine->status ? '(Không hoạt động)':''}}
                            </option>
                            @endforeach
                        </select>
                    </div>
                </div>
                <div class="clearfix"></div>
                <button class="btn btn-sm btn-flat btn-primary pull-right" type="submit">Lưu</button>        
                <div class="clearfix"></div>               
            </form>
        </div>
    </div>

    </div>
    <!-- box body -->
</div>
@endif

@stop

@section('scripts')

    <script type="text/javascript" src="{{ asset('js/pages/room/assign-machine.js') }}"></script>
	
@stop

resources/views/admin/room/create.blade.php
@extends('layouts.master')

@section('title', 'Thêm phòng')

@section ('content')

@if(empty($roomGroups))

<div class="alert alert-warning">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
    <strong>Chú ý!</strong> Chưa có nhóm phòng nên không thể thêm phòng!
</div>

@else
<div class="box box-info">
    <div class="box-header with-border">
        <h3 class="box-title">Thêm phòng</h3>
        <div class="box-tools pull-right">
            <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
            </button>
            <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
        </div>
    </div>
        <!-- /.box-header -->
    <div class="box-body">
        <form action="{{route('admin.room.store')}}" id="form-department" method="POST" class="form-horizontal" >
            @csrf
            <div class="form-group">
                <label class="control-label col-md-2">
                    Mã phòng:
                    <span class="require-field">(*)</span>
                </label>
                <div class="col-md-3">
                    <input type="text" name="roomcode" value="{{old('roomcode')}}" class="form-control">
                </div>
            </div>
            <div class="form-group">
                <label class="control-label col-md-2">
                    Tên phòng: 
                    <span class="require-field">(*)</span>
                </label>
                <div class="col-md-5">
                    <input type="text" name="name" class="form-control" value="{{old('name')}}">
                </div>
            </div>
            <div class="form-group">
                <label class="control-label col-md-2">
                    Nhóm phòng:
                </label>
                <div class="col-md-3">
                <select name="roomgroupid" class="form-control">
                    <?php
                        $currentGroup = isset($roomGroupCurrent) ? $roomGroupCurrent : old('roomgroupid');
                    ?>
                    @foreach($roomGroups as $key => $value)
                        <option {{$currentGroup == $key ? 'selected':''}} value="{{$key}}">{{$value}}</option>        
                    @endforeach
                </select>
                </div>
            </div>
            <div class="form-group">
                <label class="control-label col-md-2">
                    Ghi chú:
                </label>
                <div class="col-md-10">
                    <input type="text" name="note" value = "{{old('note')}}" class="form-control">
                </div>
            </div>

            <div class="form-group">
                <div class="col-sm-10 col-sm-offset-2">
                    <button type="submit" class="btn btn-primary">Lưu</button>
                </div>
            </div>
        </form>
    </div>
    <!-- box body -->
</div>
@endif

@stop

@section('scripts')

	<script type="text/javascript" src="{{ asset('js/jquery.validate.min.js') }}"></script>
	<script type="text/javascript" src="{{ asset('js/additional-methods.min.js') }}"></script>
    <script type="text/javascript" src="{{ asset('js/pages/room/create.js') }}"></script>
	<script type="text/javascript">
		$(function(){
			@if($errors->has('roomcode'))
				$('form#form-department').validate().showErrors({
				 	"roomcode": "{{$errors->first('roomcode')}}"
				});
          	@endif
          
		});

	</script>
@stop

resources/views/admin/room/index.blade.php
@extends('layouts.master')
@section('title', 'Quản lý phòng')
@section('content')

<!-- Danh sach may dien danh -->
<div class="box box-info">
    <div class="box-header with-border">
        <h3 class="box-title">Quản lý phòng</h3>
        <div class="box-tools pull-right">
            <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
            <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
        </div>
    </div>
    <!-- /.box-header -->
   <!-- box-body -->
    <div class="box-body">
    <!-- room group table -->
    <div class="col-md-4 col-sm-12">
        <h4 class="text-center box-title">Danh sách nhóm phòng</h4>
        <div class="box-header">
            <a href="{{route('admin.roomgroup.create')}}" class="btn btn-sm btn-info pull-right"> 
                <i class="fa fa-plus"></i> Thêm nhóm phòng
            </a>
        </div>
        <div class="clearfix">
            <table class="table no-margin">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Mã nhóm phòng</th>
                        <th>Tên nhóm phòng</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                <?php $index=1; ?>
                @foreach($roomGroups as $roomGroup)
                <tr>
                    <td class="text-center">{{$index++}}</td>
                    <td><a href="{{route('admin.room.index', ['roomgroup' => $roomGroup->id])}}"> {{$roomGroup->roomgroupcode}}</a> </td>
                    <td> {{$roomGroup->name}}</td>
                    <td>
                        <div class="dropdown">
                            <button class="btn btn-primary btn-sm btn-flat dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                                <i class="fa fa-cog"></i> <span class="caret"></span>
                            </button>
                            <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
                                <li><a href="{{route('admin.roomgroup.edit', ['id'=>$roomGroup->id])}}">
                                    <i class="fa fa-pencil"></i> Sửa
                                </a></li>
                                <li><a data-toggle="modal" href="#modal-delete-roomgroup"
                                        data-id = "{{$roomGroup->id}}" 
                                        data-title = "{{$roomGroup->roomgroupcode}}"> 
                                    <i class="fa fa-trash"></i> Xóa
                                </a></li>
                            </ul>
                        </div>
                    </td>
                </tr>
                @endforeach
                </tbody>
            </table>
        </div>
    </div>
    <!-- End room group table -->
    <!-- Room table -->
    <div class="col-md-8 col-sm-12">
        <h4 class="box-title text-center">Danh sách phòng làm việc</h4>
        <!-- form filter -->
        <div class="box-header">
            <form action="{{route('admin.room.index')}}" method="GET" class="form-inline" role="form">
                <div class="search-form col-md-10">
                    <div class="form-group">
                        <select name="roomgroup" class="form-control">
                            <option value="0">--- Nhóm phòng ---</option>        
                            @foreach($roomGroups as $roomGroup)
                            <option {{$roomGroupCurrent == $roomGroup->id ? 'selected': ''}} value="{{$roomGroup->id}}">
                                {{$roomGroup->roomgroupcode}}
                            </option>        
                            @endforeach
                        </select>
                    </div>
                    <div class="form-group">
                        <select name="status" class="form-control">
                            <option value="-1">--- Tình trạng ---</option>
                            <option {{$status == 1 ? 'selected': ''}} value="1">Đã gán máy điểm danh</option>
                            <option {{$status == 0 ? 'selected': ''}} value="0">Chưa gán máy điểm danh</option>
                        </select>
                    </div>
                    <button type="submit" class="btn btn-primary btn-flat">
                        <i class="fa fa-filter"></i> Lọc
                    </button>
                </div> 
                <div class="col-md-2">
                    <button type="submit" formaction="{{route('admin.room.create')}}" class="btn btn-sm btn-info "> 
                        <i class="fa fa-plus"></i> Thêm phòng
                    </button>
                </div>
            </form> 
        </div>
        <div class="clearfix"></div>
        <!-- end form filter -->
            <table class="table no-margin">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Mã phòng</th>
                        <th>Tên phòng</th>
                        <th>Máy điểm danh</th>
                        <th>Ghi chú</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    <?php $index=1; ?>
                    @foreach($rooms as $room)
                    <tr>
                        <td class="text-center">{{$index++}}</td>
                        <td>{{$room->roomcode}} </td>
                        <td> {{$room->name}}</td>
                        <td>
                        @foreach($room->machines as $machine)
                            <a href="{{route('admin.machine.edit', ['id' => $machine['id']])}}">
                                <label class="label {{$machine['status'] ? 'label-success' : 'label-danger'}}">
                                    {{$machine['machinecode']}} 
                                </label>
                            </a>
                            &nbsp;
                        @endforeach
                        </td>
                        <td> {{$room->note}}</td>
                        <td>
                            <div class="dropdown">
                                <button class="btn btn-primary btn-sm btn-flat dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                                    <i class="fa fa-cog"></i> <span class="caret"></span>
                                </button>
                                <ul class="dropdown-menu" aria-labelledby="dropdownMenu1"  style="right: 0; left: auto;">
                                    <li><a href="{{route('admin.room.edit', ['id'=>$room->id])}}">
                                        <i class="fa fa-pencil"></i> Sửa
                                    </a></li>
                                    <li><a data-toggle="modal" href="#modal-delete-room"
                                            data-id = "{{$room->id}}" 
                                            data-title = "{{$room->roomcode}}"> 
                                        <i class="fa fa-trash"></i> Xóa
                                    </a></li>
                                    <li><a href="{{route('admin.room.assignmachine', ['id'=>$room->id])}}">
                                        <i class="fa fa-gavel"></i> Gán máy điểm danh
                                    </a></li>
                                </ul>
                            </div>
                        </td>
                    </tr>
                    @endforeach
                    
                </tbody>
            </table>
            <!-- box footer -->
            @if(!empty($rooms))
            <div class="box-footer">
                <label class="control-label"><span class="label-success">&nbsp;&nbsp;&nbsp;&nbsp;</span> Hoạt động </label>
                &nbsp; &nbsp;
                <label class="control-label"><span class="label-danger">&nbsp;&nbsp;&nbsp;&nbsp;</span> Không hoạt động </label>
            </div>
            @endif
            <!-- end box footer -->
        </div>
    <!-- End room table -->
    </div>
   <!-- End boxbody -->
    
</div>

<!-- Modal Delete Room Group-->
<div class="modal fade" id="modal-delete-roomgroup">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Cảnh báo</h4>
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            </div>
            <form method="post" action="">
                {{csrf_field()}}
                
                <div class="modal-body">
                    <input type="hidden" id="modal-delete-id" name="id">
                    Bạn có chắc chắn xóa nhóm phòng <strong id="modal-delete-name"></strong> ?
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Không</button>
                    <button type="submit" class="btn btn-primary">Có</button>
                </div>
            </form>
        </div>
    </div>
</div>	
<!-- End modal Delete Room Group-->
<!-- Modal Delete Room -->
<div class="modal fade" id="modal-delete-room">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Cảnh báo</h4>
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            </div>
            <form method="post" action="">
                {{csrf_field()}}
                
                <div class="modal-body">
                    <input type="hidden" id="modal-delete-id" name="id">
                    Bạn có chắc chắn xóa phòng <strong id="modal-delete-name"></strong> ?
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Không</button>
                    <button type="submit" class="btn btn-primary">Có</button>
                </div>
            </form>
        </div>
    </div>
</div>	
<!-- End modal Delete Room-->
@endsection
@section('scripts')
    <script src="{{asset('js/pages/room/index.js')}}"></script>
@endsection