routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Auth::routes();


// Route::middleware('auth')->group(function(){
    Route::get('logout', 'Auth\LoginController@logout');
Route::get('/', 'HomeController@index')->name('home.index');

Route::prefix('self-enrol')->middleware('auth')->name('self-enrol.')->group(function () {
    Route::get('/', 'SelfEnrolController@index')->name('index');
    Route::post('enrol', 'SelfEnrolController@enrol')->name('enrol');
});
// Route::namespace('Admin')->middleware('auth')->group(function(){
//     Route::prefix('activity')->name('activity.')->group(function () {
//         Route::get('attendance/{id}/{section}', 'ActivityController@attendance')->name('attendance');
//         Route::get('attendance/{id?}/result-by-detail/{activityCalendarDetailId}', 'ActivityController@resultAttendanceByDetail')->name('result-attendance-by-detail');
//         Route::post('attendance/overridden/{activityCalendarDetailId}', 'ActivityController@overridenAttendance')->name('attendance-overridden');
//         Route::post('attendance/{id}/calendar', 'ActivityController@updateCalendar')->name('updatecalendar');
//         Route::post('attendance/{id}/export', 'ActivityController@exportResultAttendance')->name('attendance.export');        
//         Route::get('participant/{id}', 'ActivityController@participant')->name('participant');
//         Route::get('participant/potential-users/{id}', 'ActivityController@getPotentialUser')->name('get-potential-user');
//         Route::post('participant/enrol-users/{method?}', 'ActivityController@enrolUser')->name('enrol-user');
//         Route::post('participant/unenrol/{activityid}', 'ActivityController@unenrolUser')->name('unenrol-user');       
//         Route::get('statistic/{id}', 'ActivityController@statistic')->name('statistic');
//     });
// });
Route::namespace('Admin')->middleware('auth')->prefix('admin')->name('admin.')->group(function () {
    Route::prefix('machine')->name('machine.')->group(function () {
        Route::get('/', 'MachineController@index')->name('index');
        Route::get('index', 'MachineController@index')->name('index');
        Route::get('create', 'MachineController@create')->name('create');
        Route::post('store', 'MachineController@store')->name('store');
        Route::get('edit/{id}', 'MachineController@edit')->name('edit');
        Route::post('update', 'MachineController@update')->name('update');
        Route::get('update-identity-user/{id}', 'MachineController@showIdentityUser')->name('update-identity-user');
        Route::get('update-identity-user/{id}/get-potential-user', 'MachineController@getPotentialUser')->name('get-potential-user');
        Route::post('update-identity-user/{id}/store-identity-user', 'MachineController@storeIdentityUser')->name('store-identity-user');
        Route::post('delete-identity-user', 'MachineController@deleteIdentityUser')->name('delete-identity-user');
        Route::post('delete', 'MachineController@destroy')->name('delete');
    });

    Route::prefix('room')->name('room.')->group(function () {
        Route::get('/', 'RoomController@index')->name('index');
        Route::get('index', 'RoomController@index')->name('index');
        Route::get('create', 'RoomController@create')->name('create');
        Route::post('store', 'RoomController@store')->name('store');
        Route::get('edit/{id}', 'RoomController@edit')->name('edit');
        Route::get('assign-machine/{id}', 'RoomController@assignMachine')->name('assignmachine');
        Route::post('store-assign-machine', 'RoomController@storeAssignMachine')->name('storeassign');
        Route::post('update', 'RoomController@update')->name('update');
        Route::post('delete', 'RoomController@destroy')->name('delete');
    });
    
    Route::prefix('roomgroup')->name('roomgroup.')->group(function () {
        Route::get('create', 'RoomGroupController@create')->name('create');
        Route::post('store', 'RoomGroupController@store')->name('store');
        Route::get('edit/{id}', 'RoomGroupController@edit')->name('edit');
        Route::post('update', 'RoomGroupController@update')->name('update');
        Route::post('delete', 'RoomGroupController@destroy')->name('delete');
    });
    Route::prefix('holiday')->name('holiday.')->group(function () {
        Route::get('/', 'HolidayController@index')->name('index');
        Route::get('index', 'HolidayController@index')->name('index');
        Route::get('create', 'HolidayController@create')->name('create');
        Route::post('store', 'HolidayController@store')->name('store');
        Route::get('edit/{id}', 'HolidayController@edit')->name('edit');
        Route::post('update', 'HolidayController@update')->name('update');
        Route::post('delete', 'HolidayController@destroy')->name('delete');
    });


     Route::prefix('activitycategory')->name('activitycategory.')->group(function () {
        Route::get('create', 'ActivityCategoryController@create')->name('create');
        Route::post('store', 'ActivityCategoryController@store')->name('store');
        Route::get('edit/{id}', 'ActivityCategoryController@edit')->name('edit');
        Route::post('update', 'ActivityCategoryController@update')->name('update');
        Route::post('delete', 'ActivityCategoryController@destroy')->name('delete');
    });

    Route::prefix('activity')->name('activity.')->group(function () {
        Route::get('/', 'ActivityController@index')->name('index');
        Route::get('index', 'ActivityController@index')->name('index');
        Route::get('create', 'ActivityController@create')->name('create');
        Route::post('store', 'ActivityController@store')->name('store');
        Route::get('edit/{id}', 'ActivityController@edit')->name('edit');
        Route::post('update/{id}', 'ActivityController@update')->name('update');
        Route::get('subview-table-frequency/{frequency}/{shift?}', 'ActivityController@subViewTableFrequency')->name('subviewtablefrequency');
        Route::get('attendance/{id}/{section}', 'ActivityController@attendance')->name('attendance');
        Route::get('attendance/{id?}/result-by-detail/{activityCalendarDetailId}', 'ActivityController@resultAttendanceByDetail')->name('result-attendance-by-detail');
        Route::post('attendance/overridden/{activityCalendarDetailId}', 'ActivityController@overridenAttendance')->name('attendance-overridden');
        Route::post('attendance/{id}/calendar', 'ActivityController@updateCalendar')->name('updatecalendar');
        Route::post('attendance/{id}/export', 'ActivityController@exportResultAttendance')->name('attendance.export');        
        Route::get('participant/{id}', 'ActivityController@participant')->name('participant');
        Route::get('participant/potential-users/{id}', 'ActivityController@getPotentialUser')->name('get-potential-user');
        Route::post('participant/enrol-users/{method?}', 'ActivityController@enrolUser')->name('enrol-user');
        Route::post('participant/unenrol/{activityid}', 'ActivityController@unenrolUser')->name('unenrol-user');
       
        Route::get('statistic/{id}', 'ActivityController@statistic')->name('statistic');
        Route::post('delete', 'ActivityController@destroy')->name('delete');
    });
    Route::prefix('user')->name('user.')->group(function () {
        Route::get('/', 'UserController@index')->name('index');
        Route::get('index', 'UserController@index')->name('index');
        Route::get('create', 'UserController@create')->name('create');
        Route::post('store', 'UserController@store')->name('store');
        Route::get('edit/{id}', 'UserController@edit')->name('edit');
        Route::post('update', 'UserController@update')->name('update');
        Route::post('delete', 'UserController@destroy')->name('delete');
    });
    
    Route::prefix('cohort')->name('cohort.')->group(function () {
        Route::get('/', 'CohortController@index')->name('index');
        Route::get('index', 'CohortController@index')->name('index');
        Route::get('create', 'CohortController@create')->name('create');
        Route::post('store', 'CohortController@store')->name('store');
        Route::get('edit/{id}', 'CohortController@edit')->name('edit');
        Route::get('assign-user/{id}', 'CohortController@assignMachine')->name('assignuser');
        Route::post('store-assign-user', 'CohortController@storeAssignMachine')->name('storeassign');
        Route::post('update', 'CohortController@update')->name('update');
        Route::post('delete', 'CohortController@destroy')->name('delete');
    });

    Route::prefix('shift')->name('shift.')->group(function () {
        Route::get('/', 'ShiftController@index')->name('index');
        Route::get('index/{id?}', 'ShiftController@index')->name('index');
        Route::get('create', 'ShiftController@create')->name('create');
        Route::post('store', 'ShiftController@store')->name('store');
        Route::get('edit/{id}', 'ShiftController@edit')->name('edit');
        Route::post('update', 'ShiftController@update')->name('update');
        Route::post('delete', 'ShiftController@destroy')->name('delete');
    });

    Route::prefix('config')->name('config.')->group(function () {
        Route::get('/{section?}', 'ConfigController@index')->name('index');
        Route::post('update/{section?}', 'ConfigController@update')->name('update');

        Route::get('role/create', 'RoleController@create')->name('create-role');
        Route::post('role/store', 'RoleController@store')->name('store-role');

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'firstname', 'email', 'password', 'status', 'lastname', 'avatar', 
        'gender', 'address', 'idnumber', 'username',  'birthday'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token'
    ];

    

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    // protected $casts = [
    //     // 'email_verified_at' => 'datetime',
    // ];
    public function getFullname(){
        return $this->lastname . ' '. $this->firstname;
    }

    public function machines()
    {
        return $this->hasMany('App\UserMachine');
    }

    public function activityAttendances()
    {
        return $this->hasMany('App\ActivityAttendance');
    }

    public function activityEnrols()
    {
        return $this->hasMany('App\ActivityEnrol', 'userid');
    }

    public function userMachines(){
        return $this->hasMany('App\UserMachine', 'userid');      
    }
    
    public function roleAssignments()
    {
        return $this->hasMany('App\RoleAssignment', 'userid', 'id');
    }
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Input;
use Illuminate\Support\Facades\DB;
use Constraint;
use Illuminate\Support\Facades\Hash;
use Storage;

class UserController extends \App\Http\Controllers\Controller
{

    public function index(){
        \CheckPermission::requireCapability('system:manage_system', \ContextSystem::instance()); 
        $username = trim(Input::get('username', ''));
        $fullname = trim(Input::get('fullname', ''));
        $status = Input::get('status', -1);
        $users = User::where(function ($query) use($username, $fullname) {
            $query->where('username', 'like', '%'.$username.'%')->where(DB::raw('CONCAT(lastname, " ", firstname)'), 'like', '%'.$fullname.'%');
        });
        if($status==Constraint::USER_STATUS_TYPE_ACTIVE or $status==Constraint::USER_STATUS_TYPE_INACTIVE){
            $users = $users->where('status', $status);
        }
        $users = $users->orderBy('firstname', 'ASC')->orderBy('lastname', 'ASC')->paginate(Constraint::ITEMS_PER_PAGE); 
        // $users = $users->orderBy('firstname', 'ASC')->orderBy('lastname', 'ASC')->paginate(1); 
        if($status == -1 && empty($keyword))
            $users->withPath(route('admin.user.index'));
        else
            $users->withPath(route('admin.user.index', compact('status', 'username', 'fullname')));
        return view('admin.user.index', compact('users', 'username', 'fullname', 'status'));
    }
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        \CheckPermission::requireCapability('system:manage_system', \ContextSystem::instance()); 
        return view('admin.user.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = $request->all();
        $msgErrors = [];
        if(isset($data['idunmber']) && User::where('idunmber', $data['idunmber'])->first()){
            $msgErrors['idunmber']='Mã thành viên đã tồn tại!';
        }
        if(isset($data['username']) && User::where('username', $data['username'])->first()){
            $msgErrors['username']='Tên đăng nhập đã tồn tại!';
        }
        if(isset($data['email']) && trim($data['email']) != '' && User::where('email', $data['email'])->first()){
            $msgErrors['email']='Email đã tồn tại!';
        }
        if(!empty($msgErrors) > 0) return redirect()->back()->withInput()->withErrors($msgErrors);
        
        $data['password'] = Hash::make($data['password']);
        if(isset($data['avatar'])){
            $imgName =  time();
            // $data['Avatar'] = $imgName;
            // $path = $request->Avatar->storeAs('public/avatar', $imgName); //in Storage
            $path = Storage::putFile(Constraint::PATH_AVATAR .$imgName, $request->avatar);
            // return $path;
            $data['avatar'] = $path;
        }else{
            $data['avatar'] = null;
        }
        $user = User::create($data); 
        return redirect()->route('admin.user.index');
    }
    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        \CheckPermission::requireCapability('system:manage_system', \ContextSystem::instance());        

        $user = User::findOrFail($id);
        // $parents = self::loadParents($id);
        return view('admin.user.edit', compact('user'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request)
    {
        $data = $request->all();
        $user = User::findOrFail($data['id']);
        $msgErrors = [];

        if(isset($data['idunmber']) && $user->idnumber != $data['idnumber'] && User::where('idunmber', $data['idunmber'])->first()){
            $msgErrors['idunmber']='Mã thành viên đã tồn tại!';
        }
        if(isset($data['username']) && $user->username != $data['username'] && User::where('username', $data['username'])->first()){
            $msgErrors['username']='Tên đăng nhập đã tồn tại!';
        }
        if(isset($data['email']) && trim($data['email']) != '' && $user->email != $data['email'] && User::where('email', $data['email'])->first()){
            $msgErrors['email']='Email đã tồn tại!';
        }  
        if(!empty($msgErrors)) return redirect()->back()->withInput()->withErrors($msgErrors);
        if($data['changePassword'] && trim($data['password']) != '' )
            $data['password'] = Hash::make($data['password']);
        else{
            unset($data['password']);
        }
        if(isset($data['avatar'])){
           $imgName =  time();
           $path = Storage::putFile(Constraint::PATH_AVATAR .$imgName, $request->avatar);
           $data['avatar'] = $path;
        }else{
            unset($data['avatar']);
        }
        $user->update($data); 
        return redirect()->route('admin.user.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        //
    }
}

resources/views/admin/user/create.blade.php
@extends('layouts.master')

@section('title', 'Thêm thành viên')

@section ('content')

<div class="box box-info">
    <div class="box-header with-border">
        <h3 class="box-title">Thêm thành viên</h3>
        <div class="box-tools pull-right">
            <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
            </button>
            <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
        </div>
    </div>
        <!-- /.box-header -->
    <div class="box-body">
        <form action="{{route('admin.user.store')}}" id="form-department" method="POST" class="form-horizontal"  enctype="multipart/form-data">
                @csrf
                <div class="form-header col-md-12">
                    Thông tin tài khoản
                </div>
                <div class="form-group">
                    <label class="control-label col-md-2">
                        Tên đăng nhập: 
                        <span class="require-field">(*)</span>
                    </label>
                    <div class="col-md-3">
                        <input type="text" name="username" class="form-control" value="{{old('username')}}">
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-md-2">
                        Mật khẩu: 
                        <span class="require-field">(*)</span>
                    </label>
                    <div class="col-md-4">
                        <div class="input-group">
                            <input type="password" name="password" class="form-control" value="{{old('password')}}">
                            <span class="input-group-btn">
                                <button type="button" class="btn btn-default" id="btn-eye">
                                    <i class="fa fa-eye"></i>
                                </button>
                            </span>
                        </div>
                    </div>
                </div>
                
                <div class="form-group">
                    <label class="control-label col-md-2">
                        Trạng thái:
                    </label>
                    <div class="col-md-3">
                        <select name="status" class="form-control">
                            <option {{old('status') === '1' ? 'selected' : '' }} value="1">Kích hoạt</option>
                            <option {{old('status') === '0' ? 'selected' : '' }} value="0">Tạm ngưng</option>
                        </select>
                    </div>
                </div>

                <div class="form-header col-md-12">
                    Thông tin cá nhân
                </div>
                <div class="form-group">
                    <label class="control-label col-md-2">
                        Họ:
                        <span 
                        class="require-field">(*)</span>
                    </label>
                    <div class="col-md-5">
                        <input type="text" name="lastname" class="form-control"  value="{{old('lastname')}}">
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-md-2">
                        Tên:
                        <span class="require-field">(*)</span>
                    </label>
                    <div class="col-md-5">
                        <input type="text" name="firstname" class="form-control"  value="{{old('firstname')}}">
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-md-2">
                        Mã thành viên:
                        <span class="require-field">(*)</span>
                    </label>
                    <div class="col-md-5">
                        <input type="text" name="idnumber" class="form-control"  value="{{old('idnumber')}}">
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-md-2">
                        Ngày sinh:
                    </label>
                    <div class="col-md-5">
                        <input type="text" name="birthday" class="form-control"  value="{{old('birthday')}}">
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-md-2">
                        Giới tính:
                    </label>
                    <div class="col-md-2">
                        <?php $currentGender = old('gender'); ?>
                        <select name="gender" class="form-control">
                            <option {{$currentGender === '1' ? 'selected' : '' }} value="1">Nam</option>
                            <option {{$currentGender === '0' ? 'selected' : '' }} value="0">Nữ</option>
                            <option {{$currentGender === '2' ? 'selected' : '' }} value="2">Khác</option>
                        </select>
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-md-2">
                        Email:
                        <!-- <span class="require-field">(*)</span> -->
                    </label>
                    <div class="col-md-6">
                        <input type="text" name="email" class="form-control" value="{{old('email')}}">
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-md-2">
                        Địa chỉ:
                    </label>
                    <div class="col-md-10">
                        <input type="text" name="address" class="form-control" value = "{{old('address')}}">
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-md-2">
                        Ảnh:
                    </label>
                    <div class="col-md-10">
                        <input type="file" name="avatar">
                    </div>
                </div>
                
                
                <div class="form-group">
                    <div class="col-sm-10 col-sm-offset-2">
                        <button type="submit" class="btn btn-primary">Lưu</button>
                    </div>
                </div>
        </form>
    </div>
    <!-- box body -->
</div>
@stop

@section('scripts')

	<script type="text/javascript" src="{{ asset('js/jquery.validate.min.js') }}"></script>
	<script type="text/javascript" src="{{ asset('js/additional-methods.min.js') }}"></script>
    <script type="text/javascript" src="{{ asset('js/pages/user/create.js') }}"></script>
	<script type="text/javascript">
		$(function(){
			@if($errors->has('idnumber'))
				$('form#form-department').validate().showErrors({
				 	"idnumber": "{{$errors->first('idnumber')}}"
				});
          	@endif
            @if($errors->has('username'))
				$('form#form-department').validate().showErrors({
				 	"username": "{{$errors->first('username')}}"
				});
          	@endif
          	@if($errors->has('email'))
				$('form#form-department').validate().showErrors({
				 	"email": "{{$errors->first('email')}}"
				});
              @endif
           
		});

	</script>
@stop

resources/views/admin/user/index.blade.php
@extends('layouts.master')
@section('title', 'Thành viên')
@section('content')

<div class="nav-tabs-custom">
  <ul class="nav nav-tabs">
    <li class="active"><a href="#">Thành viên</a></li>
    <!-- <li><a href="#tab_2" data-toggle="tab">Tab 2</a></li> -->
    <li><a href="{{route('admin.cohort.index')}}">Nhóm thành viên</a></li>
    
    <li class="pull-right"><a href="#" class="text-muted"><i class="fa fa-gear"></i></a></li>
  </ul>
  <div class="tab-content">
    <div class="tab-pane active" id="tab_1">
    <!-- Danh sach thanh vien -->
      <div class="box-header">
        <h3 class="box-title">Danh sách thành viên</h3>

      </div>
      <!-- /.box-header -->
      <div class="box-header">
          <div class="search-form col-md-8 col-sm-12">
              <form action="" method="GET" class="form-inline" role="form">
                  <div class="form-group">
                      <input type="text" name="username" class="form-control" id="" placeholder="Tên đăng nhập" value="{{$username}}">
                  </div>
                  <div class="form-group">
                      <input type="text" name="fullname" class="form-control" id="" placeholder="Họ tên" value="{{$fullname}}">
                  </div>
                  <div class="form-group">
                      <select name="status" class="form-control">
                          <option value="-1">--- Tình trạng ---</option>
                          <option {{$status==1 ? 'selected' : ''}} value ="1"> Đang hoạt động</option>
                          <option {{$status==0 ? 'selected' : ''}}  value ="0"> Không hoạt động</option>
                      </select>
                  </div>
                  <button type="submit" class="btn btn-primary btn-flat">
                      <i class="fa fa-filter"></i> Lọc
                  </button>
              </form>                 
          </div> 
          <a href="{{route('admin.user.create')}}" class="btn btn-sm btn-info btn-flat pull-right"> 
              <i class="fa fa-plus"></i> Thêm thành viên
          </a>
      </div>
      <!-- /.box-footer -->

      <div class="box-body">
        <div class="table-responsive">
          <table class="table no-margin">
            <thead>
            <tr>
              <th>#</th>
              <th>Tên đăng nhập</th>
              <th>Họ tên</th>
              <th>Mã thành viên</th>
              <th>Email</th>
              <th>Ngày sinh</th>
              <th>Trạng thái</th>
              <th></th>
            </tr>
            </thead>
            <tbody>
            <?php 
              $currentPage = $users->currentPage();
              $perPage = $users->perPage();
              //$currentPage=1;
              $index = $perPage*($currentPage-1)+1; 
            ?>
              @foreach($users as $user)
                <tr>
                  <td class="text-center">{{$index++}}</td>
                  <td>{{$user->username}} </td>
                  <td><a href=""> {{$user->getFullname() }}</a></td>
                  <td>{{$user->idnumber}}</td>
                  <td>{{$user->email}}</td>
                  <td>{{$user->birthday}}</td>
                  
                  <td class="text-center">
                    <span class="label {{$user->status ? 'label-success':'label-danger'}} ">
                      {{$user->status ? 'Hoạt động': 'Không hoạt động'}}
                    </span>
                  </td>
                  <td>
                    <a href="{{route('admin.user.edit', ['id'=>$user->id])}}" class="btn btn-sm btn-warning"> <i class="fa fa-pencil"></i> Sửa</a>
                    <a  class="btn btn-sm btn-danger" data-toggle="modal" href="#modal-delete"
                      data-id = "{{$user->id}}" 
                      data-title = "{{$user->getFullname() }}"> 
                      <i class="fa fa-trash"></i> Xóa </span></a>
                  </td>
                </tr>
                @endforeach
              </tbody>
          </table>
        </div>
        <!-- /.table-responsive -->
      </div>
      <!-- /.box-body -->
      <div class="box-header clearfix">
        {{ $users->links() }}              
      </div>
      <!-- /.box-footer -->

      <!-- End Danh sach Thanh vien -->

        </div>
  </div>
  <!-- /.tab-content -->
</div>
<!-- Modal Delete -->
<div class="modal fade" id="modal-delete">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<h4 class="modal-title">Cảnh báo</h4>
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
				</div>
				<form method="post" action="{{route('admin.machine.delete')}}">
					{{csrf_field()}}
					
					<div class="modal-body">
						<input type="hidden" id="modal-delete-id" name="id">
						Bạn có chắc chắn xóa thành viên  <strong id="modal-delete-name"></strong> này cùng với các đăng ký liên quan ?
					</div>
					<div class="modal-footer">
						<button type="button" class="btn btn-default" data-dismiss="modal">Không</button>
						<button type="submit" class="btn btn-primary">Có</button>
					</div>
				</form>
			</div>
		</div>
	</div>	
<!-- End modal Delete  -->
@endsection
@section('scripts')
    <script src="{{asset('js/pages/user/index.js')}}"></script>
@endsection